### ISSUE TITLE
No support for OSX

### ISSUE THREAD

**Issue by HeyZeer0** [jagrosh/DiscordIPC#7]
DiscordIPC doesn't work with OSX, keep throwing NoDiscordClientException

**Comment by TheMonitorLizard** [comment]
Have you checked to make sure that you have a discord client correctly open?

**Comment by HeyZeer0** [comment]
of course

**Comment by ili-codes** [comment]
Not sure if I'm necroposting but has there been a fix for this?

**Comment by jagrosh** [comment]
It's on my backlog 😅. The issue here is that what [this library does](https://github.com/jagrosh/DiscordIPC/blob/master/src/main/java/com/jagrosh/discordipc/IPCClient.java#L133) doesn't match what [Discord's version](https://github.com/discordapp/discord-rpc/blob/master/src/connection_unix.cpp) does.
